const CHYY_TOTAL_IMGS = 114;
const CHYY_BG_IMGS_SHOULD_BE_PICKED = 40;
const CHYY_FM_IMGS_SHOULD_BE_PICKED = 5;

export const TOTAL_IMGS = CHYY_TOTAL_IMGS;
export const BG_IMGS_SHOULD_BE_PICKED = CHYY_BG_IMGS_SHOULD_BE_PICKED;
export const FM_IMGS_SHOULD_BE_PICKED = CHYY_FM_IMGS_SHOULD_BE_PICKED;
