name: CD

on:
  release:
    types:
      - "published"

env:
  node_version: "13.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - name: Install JS dependencies
        run: yarn install
        working-directory: ./
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy --user "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
