name: CI

on: [push]

env:
  node_version: "13.x"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        run: yarn install
      - name: Test
        run: yarn test
